In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

print(arr + 5)
print(arr * 2)

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(arr.shape)



[1 2 3 4 5]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
15
3.0
5
1
(5,)


In [2]:
#2D array or a matrix

arr = np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [6]:
import numpy as np 

arr = np.zeros((3,4))
print(arr)  

arr = np.ones((2,3))
print(arr)

arr = np.arange(1,11)
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
import pandas as pd

data = {

    "employee_id": [101,102,103],

    "name": [
        "Rahul",
        "Priya",
        "Amit"
    ],

    "salary": [
        75000,
        85000,
        65000
    ]
}

df = pd.DataFrame(data)
print(df)

   employee_id   name  salary
0          101  Rahul   75000
1          102  Priya   85000
2          103   Amit   65000


In [9]:
import pandas as pd 

df = pd.read_csv("C:\\Users\\Asus\\OneDrive\\Desktop\\HexaTraining\\June5th\\numpy\\employees.csv")

print(df)

print(df.head())  
print(df.tail())
print(df.dtypes)
print(df.info())
print(df.describe())


   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Bangalore
2          103    Amit Kumar   Data Engineering   65000     Mumbai
3          104   Sneha Patel       Data Science   95000    Chennai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Bangalore
2          103    Amit Kumar   Data Engineering   65000     Mumbai
3          104   Sneha Patel       Data Science   95000    Chennai
4          105    Farhan Ali  Cloud Engineering   80000      Delhi
   employee_id          name         department  salary       city
0          101  Rahul Sharma   Data Engineering   75000  Hyderabad
1          102   Priya Reddy     AI Engineering   85000  Banga

In [12]:
print(df["name"])

0    Rahul Sharma
1     Priya Reddy
2      Amit Kumar
3     Sneha Patel
4      Farhan Ali
Name: name, dtype: str


In [14]:
print(df[["name","salary"]])

           name  salary
0  Rahul Sharma   75000
1   Priya Reddy   85000
2    Amit Kumar   65000
3   Sneha Patel   95000
4    Farhan Ali   80000


Dataframe able to data manipulation like indexing, renaming, sorting, ,merging data frame

built-in data manipulation, optimized performance, and the ability to handle heterogeneous data types seamlessly

Supports multiple file formats